{{ config(materialized='ephemeral') }}

{% call statement('raw_fuji_carriers', fetch_result=False) %}
CREATE OR REPLACE EXTERNAL TABLE `{{ target.project }}.slv_xref.ext_fuji_carriers`
(
 carrier STRING,
 carrier_address STRING,
 carrier_city STRING,
 carrier_zip STRING,
 carrier_id STRING,
 carrier_state STRING,
 carrier_address2 STRING,
 factor FLOAT64,
 phone STRING,
 carrier_notes STRING,
 active BOOL,
 fee_schedule STRING,
 claim_type STRING,
 carrier_type STRING,
 copay_req BOOL,
 coverage INT64,
 group_id STRING,
 clia_number STRING,
 site_to_bill STRING,
 field11_constant INT64,
 use_field11_constant BOOL,
 use_field31_for_facility_name BOOL,
 bill_to_pos STRING,
 prior_auth_number19 STRING,
 edi_number STRING,
 accept_assignment BOOL,
 qualifier STRING,
 use_field19_for_narrative BOOL,
 field19_narrative STRING,
 pos STRING,
 use_tos BOOL,
 use_pos BOOL,
 billing_type STRING,
 requires_access_num BOOL,
 tos STRING,
 upin_to_use STRING,
 requires_referral_number BOOL,
 ref_qualifier STRING,
 referrer_chosen STRING,
 abn_req BOOL,
 eremit_id STRING,
 allow_eligibility BOOL,
 hpid STRING,
 requires_premium_ref_tin BOOL,
 cms17b_blank BOOL,
 cms24j_legacy_blank BOOL,
 cms24j_npi_blank BOOL,
 cms32a_npi_blank BOOL,
 cms32b_legacy_blank BOOL,
 cms33a_npi_blank BOOL,
 cms33b_legacy_blank BOOL,
 cms17b_npi_option STRING,
 cms24j_legacy_option STRING,
 cms24j_npi_option STRING,
 cms32a_npi_option STRING,
 cms32b_legacy_option STRING,
 cms33a_npi_option STRING,
 cms33b_legacy_option STRING,
 cms17b_npi_text STRING,
 cms24j_legacy_text STRING,
 cms24j_npi_text STRING,
 cms32a_npi_text STRING,
 cms32b_legacy_text STRING,
 cms33a_npi_text STRING,
 cms33b_legacy_text STRING,
 cms17b_npi_text_option BOOL,
 cms24j_legacy_text_option BOOL,
 cms24j_npi_text_option BOOL,
 cms32a_npi_text_option BOOL,
 cms32b_legacy_text_option BOOL,
 cms33a_npi_text_option BOOL,
 cms33b_legacy_text_option BOOL,
 cms17a_blank BOOL,
 cms17a_list_option BOOL,
 cms17a_text STRING,
 cms17a_text_option BOOL,
 cms17b_npi_list_option BOOL,
 cms24j_legacy_list_option BOOL,
 cms24j_npi_list_option BOOL,
 cms32a_npi_list_option BOOL,
 cms32b_legacy_list_option BOOL,
 cms33a_npi_list_option BOOL,
 cms33b_legacy_list_option BOOL,
 cms31_blank BOOL,
 cms31_list_option BOOL,
 cms31_option STRING,
 cms31_text STRING,
 cms31_text_option BOOL,
 medigap_id STRING,
 use_medigap_id BOOL,
 requires_msp BOOL,
 use_none_box11 BOOL,
 requires_bcbs_legacy BOOL,
 carrier_code STRING,
 direct_billing_id STRING,
 imagine_carrier_id STRING
)
OPTIONS (
    format = 'CSV',
    uris = ['gs://xref-ext-tables/fuji_dimensions/ingestion_timestamp=20251002_153301/raw_fuji_carriers.csv'],
    skip_leading_rows = 1,
    field_delimiter = ',',
    allow_quoted_newlines = true,
    allow_jagged_rows = true
);

{% endcall %}