{{ config(materialized='ephemeral') }}

{% call statement('raw_fuji_sites', fetch_result=False) %}
CREATE OR REPLACE EXTERNAL TABLE `{{ target.project }}.slv_xref.ext_fuji_sites`
(site_code STRING,
 site_description STRING,
 street STRING,
 city STRING,
 zip STRING,
 contact STRING,
 phone STRING,
 logo STRING,
 active BOOL,
 directions STRING,
 map STRING,
 map_description STRING,
 overread_site BOOL,
 demographics2 STRING,
 demographics1 STRING,
 states STRING,
 place_code STRING,
 tax_id STRING,
 ssn_or_ein STRING,
 pos STRING,
 modalities STRING,
 fda_cert_code STRING,
 clia_number STRING,
 remit_site STRING,
 needs_billing_integration BOOL,
 user_emits_sites_tax_id BOOL,
 npi STRING,
 group_npi STRING,
 fax STRING,
 facility_code STRING,
 easy_link_email STRING,
 easy_link_password STRING,
 default_resrc STRING,
 country STRING,
 dont_display_address_on_mam_letters BOOL,
 website_url STRING,
 service_level_agreement STRING,
 gfi_fax_maker_email STRING,
 gfi_fax_maker_first_name STRING,
 gfi_fax_maker_last_name STRING,
 patient_address_lookup BOOL,
 default_treferr_id STRING,
 pay_to_address STRING,
 site_id STRING,
 report_template_id STRING,
 imagine_integration_id STRING,
 available_to_patient BOOL,
 use_synapse_pacs_api BOOL,
 synapse_pacs_server STRING,
 synapse_api_launch_key STRING,
 use_3rd_party_image_notification BOOL,
 secure_url_encryption_key STRING,
 secure_timed STRING,
 use_secure_url BOOL,
 available_to_referrer BOOL,
 nrdr_facility_id STRING)
OPTIONS (
    format = 'CSV',
    uris = ['gs://xref-ext-tables/fuji_dimensions/ingestion_timestamp=20251002_144550/raw_fuji_sites.csv'],
    skip_leading_rows = 1,
    field_delimiter = ',',
    allow_quoted_newlines = true,
    allow_jagged_rows = true
);

{% endcall %}