{{ config(materialized='ephemeral') }}

{% call statement('raw_dim_assets', fetch_result=False) %}
CREATE OR REPLACE EXTERNAL TABLE `{{ target.project }}.slv_xref.ext_dim_assets`
(
    asset_id STRING,
    source_id STRING,
    modality_id STRING,
    asset_class_id STRING,
    asset_name STRING,
    asset_segment STRING,
    asset_description STRING,
    asset_type STRING,
    sales_lease_back BOOL,
    current_location STRING,
    location_effective_date TIMESTAMP,
    manufacturer STRING,
    model STRING,
    servicing_entity STRING,
    company_code STRING,
    in_service_date TIMESTAMP,
    is_active BOOL,
    fixed_mobile STRING,
    software_version STRING,
    unit_disposition_status STRING,
    gff_date TIMESTAMP,
    alliance_net_id STRING,
    z_insert_date TIMESTAMP,
    z_last_mod_date TIMESTAMP,
    z_last_mod_by STRING,
    interim_unit BOOL,
    on_orders_date TIMESTAMP,
    division STRING,
    hold_date TIMESTAMP,
    hold_comments STRING,
    hold_name STRING,
    is_on_hold BOOL,
    reserved_date TIMESTAMP,
    reserved_opportunity_name STRING,
    is_reserved BOOL,
    availability_date TIMESTAMP,
    tagged_opportunity_date_1 TIMESTAMP,
    tagged_opportunity_name_1 STRING,
    tagged_opportunity_state_1 STRING,
    tagged_opportunity_date_2 TIMESTAMP,
    tagged_opportunity_name_2 STRING,
    tagged_opportunity_state_2 STRING,
    tagged_opportunity_date_3 TIMESTAMP,
    tagged_opportunity_name_3 STRING,
    tagged_opportunity_state_3 STRING,
    manufacturer_serial_number STRING,
    tag_reserved_comments STRING,
    ct_slices STRING,
    availability_in_fleet BOOL,
    asset_type_description STRING,
    manufacturer_date TIMESTAMP,
    warranty_start_date TIMESTAMP,
    warranty_end_date TIMESTAMP
)
OPTIONS (
    format = 'CSV',
    uris = ['gs://xref-ext-tables/dim_data/ingestion_timestamp=20251002_153449/raw_dim_assets.csv'],
    skip_leading_rows = 1,
    field_delimiter = ',',
    allow_quoted_newlines = true,
    allow_jagged_rows = true,
    null_marker = 'NULL'
);

{% endcall %}